Oneshot mode
torproject/onionperf pull request #1
Opened 2019-01-28 14:05 UTC by ana-cc

Adds a oneshot mode to onionperf. This uses a new tgen model to attempt downloading a 5M file. Once a download has finished, onionperf exits gracefully.

2019-02-19 09:23 UTC, irl requested changes

2019-02-19 09:23 UTC, irl commented on onionperf/onionperf
> +    measure_parser.add_argument('-i', '--onion-only',
Can we make this -o?

2019-02-19 09:23 UTC, irl commented on onionperf/onionperf
> +    measure_parser.add_argument('-o', '--inet-only',
And this one -i?

2019-02-19 09:23 UTC, irl commented on onionperf/measurement.py
> +            model.OneshotModel(tgen_port="{0}".format(tgen_port), tgen_servers=server_urls, socksproxy="127.0.0.1:{0}".format(socks_port)).dump_to_file(tgen_confpath)
If these arguments are the same, can we instead assign the model to a variable and then call that?

2019-02-26 13:14 UTC, irl requested changes

2019-02-26 13:14 UTC, irl commented on onionperf/measurement.py
>                  # collect lines until the queue is empty for a full second
This comment is not valid anymore.

2019-02-26 15:15 UTC, ana-cc commented on onionperf/measurement.py
>                  # collect lines until the queue is empty for a full second
Have removed comment in 852e90e

2019-02-26 15:21 UTC, irl commented
Rebased and merged.

2019-02-26 15:21 UTC, closed without merging